# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd1e3cb8d1568431bdb5a94604166fa54685fb057f4ae852443126bc184dfaacc2f97ded8ef443c96f59b99979ff4027ccd55ae1e669939f00a45905fc81dcf

test:
  secret_key_base: 463068a29107cfb3f08fcbe4e677f4991fbcfb97d22eac78a5983a4c381ca00ed57d199e9749b645a78f2f85844c265dc4d9eebb4ee43a792c9d4e051ad8e22d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
